name: 'install'
description: 'install the depdendencies'

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - uses: actions/cache@v2
      id: cache
      with:
        path: ./node_modules
        key: modules-${{ hashFiles('package-lock.json') }}
    - name: install
      run: |
        if echo ${{ steps.cache.outputs.cache-hit }} | grep -c "true"
        then
          echo "Cache hit - skipping dependency installation"
        else
          npm ci
        fi
      shell: bash

