on: [push]

name: 'CI'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CI: true

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./install
      - name: lint
        run: npm run lint
      - name: typecheck
        run: npm run typecheck
      - name: test
        run: npm run test

  dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./install
      - name: depcheck
        run: npm run depcheck
      - name: audit
        run: npm run audit

  build-release:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    needs: [ci]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v2
      - uses: ./install
      - name: build
        run: npm run build

      - name: Windows Release
        uses: softprops/action-gh-release@v1
        if: ${{ runner.os == 'Windows' }}
        with:
          files: ./dist/capra_web_ui_setup.exe
          prerelease: true

      - name: Ubuntu Release
        uses: softprops/action-gh-release@v1
        if: ${{ runner.os == 'Linux' }}
        with:
          files: ./dist/capra_web_ui_setup.deb
          prerelease: true

