on:
  pull_request:
  push:
    branches-ignore:
      - 'dependabot/**'

name: CI

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CI: true

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: install
        run: npm ci
      - name: lint
        run: npm run lint
      - name: typecheck
        run: npm run typecheck
      - name: test
        run: npm run test

  dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: install
        run: npm ci
      - name: depcheck
        run: npm run depcheck
      - name: audit
        run: npm run audit

  build-release:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        node-version: [16]
    runs-on: ${{ matrix.os }}
    needs: [ci]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Build
        run: npm run build

      - name: Windows Release
        uses: softprops/action-gh-release@v1
        if: matrix.os == 'windows-latest'
        with:
          files: ./dist/capra_web_ui_setup.exe
          draft: true
          prerelease: true

      - name: Ubuntu Release
        uses: softprops/action-gh-release@v1
        if: matrix.os == 'ubuntu-latest'
        with:
          files: ./dist/capra_web_ui_setup.deb
          draft: true
          prerelease: true

