on: [push]

name: 'CI'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CI: true

jobs:
  install:
    # Run the install step before anything else so we can reuse the cache in other jobs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/install

  ci:
    # run various quality checks
    needs: [install]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/install
      - name: ci
        run: npm run ci

  dependencies:
    # Makes sure we don't have unnecessary dependencies or audit errors
    needs: [install]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/install
      - name: dependencies
        run: npm run dependencies

  build-release:
    # Builds the app and creates a new release
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    needs: [ci]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/install
      - name: build
        run: npm run build

      - name: Windows Release
        uses: softprops/action-gh-release@v1
        if: ${{ runner.os == 'Windows' }}
        with:
          files: ./dist/capra_web_ui_setup.exe
          prerelease: true

      - name: Ubuntu Release
        uses: softprops/action-gh-release@v1
        if: ${{ runner.os == 'Linux' }}
        with:
          files: ./dist/capra_web_ui_setup.deb
          prerelease: true

