on: [push]

name: dependencies

env:
  CI: true

jobs:
  dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: install
        run: npm run ci
      - name: depcheck
        run: npm run depcheck
      - name: audit
        run: npm run audit
