on: [push]

name: Test Build Release

jobs:
  lint-depcheck-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm ci
        run: npm ci
        env:
          CI: true
      - name: lint
        run: npm run lint
      - name: typecheck
        run: npm run typecheck
      - name: depcheck
        run: npm run depcheck
      - name: audit
        run: npm run audit
      - name: test
        run: npm run test

  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        node-version: [16]
    runs-on: ${{ matrix.os }}
    needs: [lint-depcheck-test]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Build
        run: npm run build
        env:
          CI: true

  release:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        node-version: [16]
    runs-on: ${{ matrix.os }}
    needs: [build]
    steps:
      # WINDOWS
      - name: Windows Release
        uses: softprops/action-gh-release@v1
        if: matrix.os == 'windows-latest'
        with:
          files: ./dist/capra_web_ui_setup.exe
          draft: true
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Ubuntu
      - name: Ubuntu Release
        uses: softprops/action-gh-release@v1
        if: matrix.os == 'ubuntu-latest'
        with:
          files: ./dist/capra_web_ui_setup.deb
          draft: true
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

