on: [push]

name: Test Build Release

jobs:
  lint-depcheck-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15]

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm lint/typecheck/test
        run: |
          npm ci
          npm run lint
          npm run typecheck
          npm run depcheck
          npm test
        env:
          CI: true

  build-release:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        node-version: [15]
    runs-on: ${{ matrix.os }}
    needs: [lint-depcheck-test]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          npm ci
          npm run build
        env:
          CI: true

      # WINDOWS
      - name: Windows Release
        uses: softprops/action-gh-release@v1
        if: matrix.os == 'windows-latest'
        with:
          files: ./dist/capra_web_ui_setup.exe
          draft: true
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Ubuntu
      - name: Ubuntu Release
        uses: softprops/action-gh-release@v1
        if: matrix.os == 'ubuntu-latest'
        with:
          files: ./dist/capra_web_ui_setup.deb
          draft: true
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
